### ISSUE TITLE
p-value is not reported in streme v5.3.0 with fix

### ISSUE THREAD

**Issue by mehrankr** [kaitlin309/PRIESSTESS#1]
Hello,

I am posting this issue and its fix in case others have the same problem.

I tried installing the software on an Ubuntu serve and got it running with the following dependencies:

MEME-SUITE Streme: 5.3.0
Python: 3.8.13
RNAfold: 2.4.18
skopt: 0.9.0

I noticed the run fails eventhough I have put PRIESSTESS is in PATH.
I think more instructions on that are needed. 

Anyways, I edited the PRIESSTESS file this way and got it working:

```
# Establish package installation location
# libpath=`whereis PRIESSTESS | cut -f 2 -d ' '`
# libpath="/h/mkarimza/software/PRIESSTESS"
# libpath=${libpath%/PRIESSTESS}
# libpath="${libpath}/bin"
libpath=/h/mkarimza/software/PRIESSTESS/bin
```

Now the new error is:
```
Traceback (most recent call last):
  File "/h/mkarimza/software/PRIESSTESS/bin/utils/log2_scinot.py", line 6, in <module>
    num=sys.argv[1]
IndexError: list index out of range
(standard_in) 2: syntax error
Traceback (most recent call last):
  File "/h/mkarimza/software/PRIESSTESS/bin/utils/log2_scinot.py", line 6, in <module>
    num=sys.argv[1]
IndexError: list index out of range
(standard_in) 2: syntax error
Traceback (most recent call last):
  File "/h/mkarimza/software/PRIESSTESS/bin/PRIESSTESS_logistic_regression.py", line 18, in <module>
    trainset = np.loadtxt(trainfile, delimiter='\t', skiprows=1)
  File "/h/mkarimza/anaconda3/envs/benchmark/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1081, in loadtxt
    next(line_iter)
StopIteration
Traceback (most recent call last):
  File "/h/mkarimza/software/PRIESSTESS/bin/test_PRIESSTESS_model.py", line 17, in <module>
    trainset = np.loadtxt(trainfile, delimiter='\t', skiprows=1)
  File "/h/mkarimza/anaconda3/envs/benchmark/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1081, in loadtxt
    next(line_iter)
StopIteration
```

I started taking track of the log2_scinot command usage in PRIESSTESS and noticed no p-value gets stored by:
```
pval=`grep -A 1 "MOTIF ${i}-" streme.txt | grep -o "P=[ e.0-9-]*" | grep -o "[e\.0-9-]*"`
```

After examining the streme.txt output, I noticed MEME-Suite doesn't output p-value in that version, and they claim:

```
The E-value is the p-value multiplied by the number of motifs reported by STREME
```

I am now using:

```
evalue=`grep -A 1 "MOTIF ${i}-" streme.txt | grep -o "E=[ e.0-9-]*" | grep -o "[e\.0-9-]*"`
nsites=`nsites=`grep -A 1 "MOTIF ${i}-" streme.txt | grep nsites | tr " " "\n" | grep -A 1 nsites | tail -1``
pval=$(awk "BEGIN { print $evalue / $nsites }")
```

I elso ended up editing the log2_scinot file as
```
import math
import sys

if __name__ == "__main__":
    # takes a number in the format 1.6e-300 or 4e3 and takes log2
    num=sys.argv[1]
    try:
        num_vec=num.split("e")
        print(math.log(float(num_vec[0]), 2) + (float(num_vec[1])*math.log(10, 2)))
    except Exception:
        print(math.log(float(num), 2))
```

And now it runs fine.

**Comment by kaitlin309** [comment]
Thank you Mehran! 

Firstly, I will update the instructions for installation. I developed the package in CentOS and that method I used for the libpath must not translate well to Ubuntu.

Secondly, thank you for pointing out this issue with STREME. My version of STREME (which states it is 5.3.0 and was downloaded in early 2021) produces a P-value, but I do see that on the website now it shows the outputs contain E-values.  I will update PRIESSTESS accordingly so that it works whether there is a P-value or an E-value. 

For anyone reading this - this issue will be fixed by September 15th, 2022. I will add another comment when it is completed.

**Comment by EidrianGM** [comment]
The same issue happens with meme-5.5.1 from February 2023

**Comment by kaitlin309** [comment]
Hi Adrian! I just updated the PRIESSTESS script. Specifically, I replaced line 663 with the following:

```
	    # Check if p-value or e-value available based on STREME version
	    ppresent=`grep -A 1 "MOTIF ${i}-" streme.txt | grep -o " P=" | wc -c`
	    if [ $ppresent -lt 2 ]; then 
	        # E-value available, calculate p-value
	        evalue=`grep -A 1 "MOTIF ${i}-" streme.txt | grep -o "E=[ e.0-9-]*" | grep -o "[e\.0-9-]*"`
               nsites=`grep -A 1 "MOTIF ${i}-" streme.txt | grep -o "nsites= [0-9]*" | grep -o "[0-9]*"`
               pval=$(awk "BEGIN { print $evalue / $nsites }")
	    else
	        # P-value available
               pval=`grep -A 1 "MOTIF ${i}-" streme.txt | grep -o "P=[ e.0-9-]*" | grep -o "[e\.0-9-]*"`
	    fi
```

Can you check if this update works for you? If it does I will close the issue.

**Comment by EidrianGM** [comment]
It works, but some extra errors appeared that I could solve easily. 

1. log2_scinot.py
It was expecting the format 1.6e-30 but in my case it was receiving 1,6e-30 so I simply added to the num variables .replace(',','.'). There is probably a smarter way to solve it. Anyway the script i used: 
``` python
if __name__ == "__main__":
    # takes a number in the format 1.6e-300 or 4e3 and takes log2
    num=sys.argv[1]
    try:
        num_vec=num.split("e")
        print(math.log(float(num_vec[0].replace(',','.')), 2) + (float(num_vec[1].replace(',','.'))*math.log(10, 2)))
    except Exception:
        print(math.log(float(num.replace(',','.')), 2))
```

2. in the package skopt I got this error 
``` bash
  File "/data/realServices/jorge/datos/geneSelection/PRIESSTESS_pipeline/venv/lib/python3.8/site-packages/skopt/space/transformers.py", line 275, in inverse_transform
    return np.round(X_orig).astype(np.int)
  File "/data/realServices/jorge/datos/geneSelection/PRIESSTESS_pipeline/venv/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```
for this I simply followed the error message and changed all np.int to int in transformers.py, lines 262 and 275.

And everything worked. 

P.S.: the fold_and_annotate.sh script is quite consuming, I don't know if it is necessary to run the whole pipeline to obtain good results, but it would be great that if intermediary steps are already done the script simply goes to the next one. At least when errors appears this might be a desired function, to solve them and continue.

**Comment by kaitlin309** [comment]
Just wanted to note that I updated log2_scinot.py to deal with commas.
