### ISSUE TITLE
Confusion about the scoring step of PFMs

### ISSUE THREAD

**Issue by yuxu-1** [kaitlin309/PRIESSTESS#4]
Hi Kaitlin,

I'm reading this paper and don't understand how you **score** the 40 PFMs derived from **STREME**. 
It's little bit hard to find this part in your code for easy understanding the process. Could you have a pseudo-code or a simple plot for that?

Are the input of LR model the scores of PFMs? I saw the step to load trainfile in the code of PRIESSTESS_logistic_regression.py, but can't found the example trainfile or the related instruction for this.

Thanks
YU

**Comment by kaitlin309** [comment]
Hi YU,

Yes, the input to the LR model is a matrix where samples are individual sequences (positive and negative), and the features are the scores of the PFMs from all 7-alphabet annotations on the sequences. I will go into possibly more detail than you need, but I want to be thorough. 

#### General overview
Here is a direct link to Figure 1 in the paper: 
[Figure1.pdf](https://github.com/kaitlin309/PRIESSTESS/files/9717815/Figure1.pdf)
In C, you can a mini version of a matrix for a single alphabet, each column is PFM, and each row is a positive or negative sequence. In the cells are the scores of the PFMs on each sequence. 

In D, you can see a mini version of the the matrix that is actually used as input for the model. This matrix is a combination of all 7 matrices (one per alphabet). So the actual input might be something like this (I didn't include all 7 alphabets for the space, but this gives you an idea):

```
class	seq-4_PFM-1	seq-4_PFM-2	seq-4_PFM-3	seq-struct-8_PFM-1	seq-struct-8_PFM-2	seq-struct-16_PFM-1	struct-4_PFM-1	struct-7_PFM-1	struct-7_PFM-2
1	0.00374		0.00448		4.1186e-05	0.00069			0.07127			0.15289			0.00095		0.00028		0.00022
1	0.00038		0.00172		4.5089e-05	0.00885			0.08188			0.04466			0.00155		0.00029		1.2981e-05
0	0.00373		0.00083		0.00095	        0.08163			0.02096			0.00351			0.00488		0.00492		0.00032
0	0.00681		0.00235		0.00946	        0.00196			0.08098			0.00010			0.00089		0.00052		3.9486e-05
```
#### PFM scanning (how the scores are generated)
The actual code for this task is in `PRIESSTESS/bin/PFM_scan.py`. There is a docstring at the top of the file that describes what the script does, however, I have also generated this figure that shows how sequence scanning works: 
[Sequence.Scoring.pdf](https://github.com/kaitlin309/PRIESSTESS/files/9724750/Sequence.Scoring.pdf)

Let me know if have any questions.

**Comment by yuxu-1** [comment]
Hi Kaitlin,

Thanks for your explanation!!

Yu
