### ISSUE TITLE
PRIESSTESS_scan has trouble finding "../arguments.txt"

### ISSUE THREAD

**Issue by byee4** [kaitlin309/PRIESSTESS#5]
And also "N_score". It looks like the following line needs to be modified to find the correct arguments.txt file and the appropriate N_score variable?

https://github.com/kaitlin309/PRIESSTESS/blob/f4db2a85fe5f9a7338856719b2e1ad32016237f9/PRIESSTESS_scan#L366

should be changed to?

```
N_score=`grep "^scoreN" ../PRIESSTESS_arguments.txt | cut -f 2  --delimiter ' '`
```

**Comment by kaitlin309** [comment]
Thank you for catching this Brian! I am sorry, that whole line of code is riddled with issues! 
It has now been updated:

```
N_score=`grep "^scoreN" ../PRIESSTESS_arguments.txt | cut -f 2 -d ' '`
```
