### ISSUE TITLE
Issues with output model

### ISSUE THREAD

**Issue by Rishav1805** [kaitlin309/PRIESSTESS#6]
I am trying to analyze the output .sav file on the SPSS statistics software but the file appears unreadable. 
Also, its not exactly clear how the output data should be analyzed and interpreted.

**Comment by kaitlin309** [comment]
The ".sav" file is created with the pickle package: https://docs.python.org/3/library/pickle.html

To open `PRIESSTESS_model.sav` you can run the following in Python code:

```
import pickle
lr = pickle.load(open("PRIESSTESS_model.sav", 'rb'))
```

The variable `lr` will hold the logistic regression model trained when PRIESSTESS is run (training is performed in the script `PRIESSTESS/bin/PRIESSTESS_logistic_regression.py`).

This is an instance of the scikit-learn LogisticRegression class. Further information on class attributes and methods can be found here : https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

See also `PRIESSTESS/bin/test_PRIESSTESS_model.py` for how `PRIESSTESS_model.sav` is loaded and used for scanning other sequences.
