### ISSUE TITLE
KeyError: 'TE' annotate_alphabets.py DNA masked fastas

### ISSUE THREAD

**Issue by EidrianGM** [kaitlin309/PRIESSTESS#8]
Hi!
I was trying to run the basic command of PRIESSTESS with two masked DNA fastas, that contain also N's. Actually, one sequence is all N's, which makes no sense but it is a product of my pipeline and I was not expecting to have to control it. I thought of using the masked genome to reduce noisy results but I might be loosing motifs, Right?

My command:
`PRIESSTESS -fg FASTA1.fa -bg FASTA2.fa`

and got the following error:

```bash
Traceback (most recent call last):
  File "/data/realServices/jorge/software/PRIESSTESS/bin/annotate_alphabets.py", line 71, in <module>
    seq_struct_28 = ''.join([combo2letter_seq_struct_28[seq_4[i] + struct_7[i]] for i in N])
KeyError: 'TE'
```

The pipeline continued witih RNAfold step but the error appeared again when reaching the STREME step:

```bash
Traceback (most recent call last):
  File "/data/realServices/jorge/software/PRIESSTESS/bin/annotate_alphabets.py", line 71, in <module>
    seq_struct_28 = ''.join([combo2letter_seq_struct_28[seq_4[i] + struct_7[i]] for i in N])
KeyError: 'TE'
Identifying motifs with alphabet seq-4
ERROR: cannot open file "fg_STREME.fa" or file "fg_STREME.fa" is empty
ERROR: There was a problem reading the primary sequence file 'fg_STREME.fa'.
Identifying motifs with alphabet seq-struct-8
ERROR: cannot open file "fg_STREME.fa" or file "fg_STREME.fa" is empty
ERROR: There was a problem reading the primary sequence file 'fg_STREME.fa'.
Identifying motifs with alphabet seq-struct-16
ERROR: cannot open file "fg_STREME.fa" or file "fg_STREME.fa" is empty
ERROR: There was a problem reading the primary sequence file 'fg_STREME.fa'.
Identifying motifs with alphabet seq-struct-28
ERROR: cannot open file "fg_STREME.fa" or file "fg_STREME.fa" is empty
ERROR: There was a problem reading the primary sequence file 'fg_STREME.fa'.
Identifying motifs with alphabet struct-2
ERROR: cannot open file "fg_STREME.fa" or file "fg_STREME.fa" is empty
ERROR: There was a problem reading the primary sequence file 'fg_STREME.fa'.
Identifying motifs with alphabet struct-4
ERROR: cannot open file "fg_STREME.fa" or file "fg_STREME.fa" is empty
ERROR: There was a problem reading the primary sequence file 'fg_STREME.fa'.
Identifying motifs with alphabet struct-7
ERROR: cannot open file "fg_STREME.fa" or file "fg_STREME.fa" is empty
ERROR: There was a problem reading the primary sequence file 'fg_STREME.fa'.
```

How could I avoid this issue?

**Comment by kaitlin309** [comment]
Hi! 

The error is almost certainly being thrown because your FASTA files have "T"s instead of "U"s. I can add something to the code to handle this, but in the meantime if you convert the "T"s to "U"s in your FASTA files, it should work:

```
cat FASTA1.fa | tr 'T' 'U' > FASTA1_U.fa
cat FASTA2.fa | tr 'T' 'U' > FASTA2_U.fa
PRIESSTESS -fg FASTA1_U.fa -bg FASTA2_U.fa
```

Let me know if that doesn't fix it and I can help you figure out what it could be instead.

Also, with regards to the "N"s in your files, this might pose a problem when running PRIESSTESS. One of the first steps filters out all sequences with "N"s. So if a lot of the sequences have "N"s, there won't be much data to work with. If you want to talk about that in more detail let me know! (Feel free to email me directly.)

**Comment by kaitlin309** [comment]
Hi again, I just realized that these files are FASTAs (or at least that is the extension), but PRIESSTESS actually takes files without sequence names. I am not sure if you are removing the names and just saving them with a ".fa" extension, but if not, then you should remove them before passing them to PRIESSTESS.

Here is the relevant section from the README:

`PRIESSTESS_scan -fg foreground_file -bg background_file [OPTIONS]`

The foreground_file and background_file must contain 1 probe sequence per line containing only characters A, C, G, U and N. Files must be either uncompressed or gzipped. To convert a fasta to the correct format use:

`awk 'NR%2==0' fasta_file.fa > correct_format.txt`

**Comment by EidrianGM** [comment]
Thanks I noticed that I skipped that part on the readme, sorry for that. I ended up transforming my DNA fastas by a combination of the two commands you have written here:

```bash
awk 'NR%2==0' FASTA1.fa | tr 'T' 'U' > FASTA1_U.fa
awk 'NR%2==0' FASTA2.fa | tr 'T' 'U' > FASTA2_U.fa

PRIESSTESS -fg FASTA1_U.fa -bg FASTA2_U.fa
 ```

**Comment by kaitlin309** [comment]
Let me know if you have any more issues/questions!
